//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YazilimSinamaProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCalisanlar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCalisanlar()
        {
            this.tblYetkililer = new HashSet<tblYetkililer>();
            this.tblZimmet = new HashSet<tblZimmet>();
        }
    
        public int calisanID { get; set; }
        public string adi { get; set; }
        public string soyadi { get; set; }
        public Nullable<System.DateTime> dogumTarihi { get; set; }
        public string cinsiyet { get; set; }
        public Nullable<decimal> maas { get; set; }
        public int depatmanID { get; set; }
        public bool aktiflikDurumu { get; set; }
    
        public virtual tblDepartman tblDepartman { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblYetkililer> tblYetkililer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblZimmet> tblZimmet { get; set; }
    }
}
