//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YazilimSinamaProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDepo
    {
        public Nullable<int> depoID { get; set; }
        public int urunSirasi { get; set; }
        public int urunID { get; set; }
        public Nullable<System.DateTime> satinAlmaTarihi { get; set; }
        public Nullable<int> adet { get; set; }
    
        public virtual tblUrun tblUrun { get; set; }
    }
}
