//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YazilimSinamaProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblYetkililer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblYetkililer()
        {
            this.tblZimmet = new HashSet<tblZimmet>();
        }
    
        public int yetkiliID { get; set; }
        public int CalisanID { get; set; }
        public int rolID { get; set; }
        public string kullaniciAdi { get; set; }
        public string sifre { get; set; }
    
        public virtual tblCalisanlar tblCalisanlar { get; set; }
        public virtual tblRol tblRol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblZimmet> tblZimmet { get; set; }
    }
}
