//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YazilimSinamaProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblZimmet
    {
        public int zimmetID { get; set; }
        public int yetkiliID { get; set; }
        public int urunID { get; set; }
        public int calisanID { get; set; }
    
        public virtual tblCalisanlar tblCalisanlar { get; set; }
        public virtual tblUrun tblUrun { get; set; }
        public virtual tblYetkililer tblYetkililer { get; set; }
    }
}
